version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-production:
        dependency-type: production
      web-development:
        dependency-type: development
